wasmCloud/wasmcloud-otp

host_core/lib/host_core/web_assembly/imports.ex
This is just a refactoring that removed dependency on the now-deleted native RPC call from inside the rustler NIF. Now we're just gathering up the right data and then making a request on the right subject via Gnat. This code should look a lot like our invocation test.
I don't have a test for this one yet since we don't actually have a capability provider we can test with. Once we get a testable provider in place, we can write a test that uses something more full-featured like the "kv counter" actor.
=> Switching host call invoker to gnat request

wasmcloud_host/.gitignore, wasmcloud_host/assets/vendor/wasmcloud/js/extra.js, wasmcloud_host/lib/wasmcloud_host_web/templates/layout/root.html.leex
Removed a temporary file that VScode decided to create, and added it to the gitignore.
That's about it for this PR, nothing to see here.
=> Ignore temporary files

capability-providers/keyvalue/rust/src/generated.rs, capability-providers/keyvalue/rust/src/main.rs, capability-providers/keyvalue/rust/src/rpc.rs
PR commit prior to pairing on kvcounter actor work.
=> Adding RPC operations support to kv provider

wasmcloud_host/lib/wasmcloud_host_web/controllers/actor_controller.ex, wasmcloud_host/lib/wasmcloud_host_web/controllers/linkdefs_controller.ex, wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.leex, wasmcloud_host/lib/wasmcloud_host_web/router.ex, wasmcloud_host/lib/wasmcloud_host_web/templates/layout/definelinkmodal.html.leex, wasmcloud_host/lib/wasmcloud_host_web/templates/layout/root.html.leex
This PR adds link def dropdown support for easier linking, as well as a few UI improvements.
=> Link dropdown autofill

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/cloud_event.ex, host_core/lib/host_core/host.ex
"Empty host" heartbeat:
```
[#68] Received on [wasmbus.ctl.default.events]: '{"data":{"actors":[],"providers":[]},"datacontenttype":"application/json","id":"80da2cf7-2e20-429c-a5f0-c67361853dd1","source":"NA5SDLHU4GCCKA5KHEQUY2OIQBCOVMSXQ52GOQYYIWTXIE3YKY5BWLLU","specversion":"1.0","time":"2021-06-28T17:36:10.219527Z","type":"com.wasmcloud.lattice.host_heartbeat"}
```
Single actor heartbeat:
```
[#70] Received on [wasmbus.ctl.default.events]: '{"data":{"actors":[{"actor":"MADQAFWOOOCZFDKYEYHC7AUQKDJTP32XUC5TDSMN4JLTDTU2WXBVPG4G","instances":1}],"providers":[]},"datacontenttype":"application/json","id":"d3c2207b-def0-4f47-bc95-d2c58cfa53e1","source":"NA5SDLHU4GCCKA5KHEQUY2OIQBCOVMSXQ52GOQYYIWTXIE3YKY5BWLLU","specversion":"1.0","time":"2021-06-28T17:36:40.250621Z","type":"com.wasmcloud.latti …
```
=> Host emits heartbeats

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/web_assembly/imports.ex
=> replace frodobuf with wasmbus for webassembly imports

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/heartbeat_emitter.ex, host_core/lib/host_core/providers/provider_module.ex, host_core/test/e2e/echo_test.exs, wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
Fixing provider health check topic, moving events topic to `wasmbus.evt.(prefix)`
=> Topic fixes

host_core/native/hostcore_wasmcloud_native/src/inv.rs, host_core/native/hostcore_wasmcloud_native/src/lib.rs
=> Adding the operation name to the invocation hash

host_core/lib/host_core/actors/actor_supervisor.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/providers/provider_supervisor.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/test/host_core_test.exs
=> Adding a purge function to HostCore.Host that empties actors and providers gracefully

host_core/lib/host_core/providers/builtin/logging.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/test/e2e/kvcounter_test.exs
=> Implement the built-in logging provider

capability-providers/httpserver/go/main.go, capability-providers/keyvalue/rust/src/main.rs, wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.leex, wasmcloud_host/lib/wasmcloud_host_web/templates/layout/root.html.leex, wasmcloud_host/mix.exs
Working on https://github.com/wasmCloud/wasmCloud/issues/216 (widgets)
This PR also adds the invocation seed to the expected HostData struct for both httpserver and redis providers. These both broke in some aspect, but now they are back to working status and are published at the following URLs.
1. `wasmcloud.azurecr.io/httpserver:0.13.1`
1. `wasmcloud.azurecr.io/redis:0.13.1`
=> Add invocation seed to HostData, fill washboard widgets with real data

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/application.ex, host_core/lib/host_core/claims/manager.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/nats.ex, host_core/test/e2e/echo_test.exs, host_core/test/host_core/actors_test.exs, host_core/test/host_core/wasmcloud/native_test.exs, host_core/test/host_core_test.exs, wasmcloud_host/lib/wasmcloud_host_web/controllers/probe_controller.ex, wasmcloud_host/lib/wasmcloud_host_web/router.ex
I created #146 as a follow-on to #69 so that the probes will be updated once the application is using a durable JetStream, with the results of the probes reflecting the status of the RPC and control connections and the stream, etc.
=> Readiness and liveness probes

host_core/lib/host_core/control_interface/server.ex, host_core/lib/host_core/providers/provider_module.ex
=> Enabling port monitoring of provider executable

host_core/lib/host_core/application.ex, host_core/lib/host_core/jetstream/cache_loader.ex
=> Add a registry for cache loader event watchers

.github/workflows/build_tarballs_manual.yml
Creating this for the time being so we can test our build/release pipeline with a manual dispatch
=> Manual tarball build action

LICENSE, README.md, capability-providers/README.md, host_core/README.md, wasmcloud_host/README.md
=> Updating READMEs

host_core/Makefile, host_core/test/host_core/wasmcloud/native_test.exs, host_core/test/support/constants.exs
Signed-off-by: stevelr <steve@cosmonic.com>
=> update tests to httpserver:0.14.3

wasmcloud_host/lib/wasmcloud_host_web/live/components/start_actor_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/page_live.ex
=> Select embedded host, update stale OCI refs

.github/workflows/build_tarballs_manual.yml, .gitignore, host_core/config/prod.exs, wasmcloud_host/config/prod.exs
Please note that this does not try to consolidate any of the pipelines and the windows pipeline differs from the others. For purposes of expediency, we are doing it this way and have #223 open to track the cleanup
=> Adds windows tarballs to pipeline

host_core/lib/host_core/host.ex
=> Add the cluster issuers list to the host data structure

wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
=> Converting unnecessary info logs to debug

host_core/lib/host_core/web_assembly/imports.ex, host_core/test/e2e/kvcounter_test.exs
Signed-off-by: stevelr <steve@cosmonic.com>
=> improve invocation error message when actor is missing capability claim

host_core/lib/host_core/control_interface/server.ex
This is super basic and doesn't support completely graceful shutdown, but
it should be a good start for automating host shutdowns
=> feat(host): Adds stop host command

host_core/lib/host_core/control_interface/server.ex, host_core/lib/host_core/host.ex
Apologies I didn't catch this before @thomastaylor312 - context switching from Rust made me forget the pattern we've been using to acknowledge commands.
=> Host now ACKs the host stop command

wasmcloud_host/chart/Chart.yaml, wasmcloud_host/chart/README.md, wasmcloud_host/chart/templates/deployment.yaml, wasmcloud_host/chart/templates/leafnode.yaml, wasmcloud_host/chart/values.yaml
Also bumps the app version to 0.50.2
=> feat(chart): Adds support for the new jetstream domain fix

host_core/lib/host_core.ex, host_core/lib/host_core/control_interface/server.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/providers/provider_module.ex, host_core/lib/host_core/providers/provider_supervisor.ex
=> Adding support for config_json field to provider host data

.github/workflows/wasmcloud_host.yml, wasmcloud_host/chart/README.md
This is triggered on tag builds or on a trigger.
=> feat(ci): Adds auto helm chart build

wasmcloud_host/chart/Chart.yaml, wasmcloud_host/chart/templates/secret.yaml
The `or` clause for the secret was only checking if one of the possible
values was set. This now fixes it to make sure that any of them will
trigger secret creation
=> fix(chart): Fixes missing secret

wasmcloud_host/chart/Chart.yaml, wasmcloud_host/chart/templates/deployment.yaml
My original chart was just hitting the washboard, then I learned about
the `livez` and `readyz` endpoints. Ask your doctor if these endpoints
could be right for you!
=> ref(chart): Uses the proper health check endpoints

wasmcloud_host/chart/templates/deployment.yaml, wasmcloud_host/chart/templates/secret.yaml, wasmcloud_host/chart/values.yaml
This now exposes the values for setting the registry username and
password for a private registry
=> feat(chart): Adds registry authentication to chart

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/providers/provider_module.ex
Also adds `contract_id` to provider stopped event.
=> Adds image ref to various events

.github/workflows/release.yml
=> Add working-directory back to release action

wasmcloud_host/chart/templates/NOTES.txt, wasmcloud_host/chart/templates/deployment.yaml, wasmcloud_host/chart/values.yaml
This adds a few changes to the chart and adds support for host labels
=> feat(chart): Streamlines some chart things

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Issue templates are very helpful for feedback, and they were missing in this repository.
=> Added issue templates for the repo

wasmcloud_host/lib/wasmcloud_host_web/endpoint.ex
=> Allows dashboard host to be configured at runtime

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
=> 0.52.0 Release

wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/components/link_row_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/components/provider_row_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
- Add the first 5 characters of the Actor and Provider ID to the copy button
- Remove Host ID copy from the Actor and Provider section
=> Issue 334: Cleanup Actor and Provider Copy icons

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
=> Bumped versions for 0.52.4 release

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
=> bumped versions for 0.52.5 with dockerfile fix

host_core/lib/host_core/providers/provider_module.ex
=> Terminate provider module when linked binary stops

.github/workflows/wasmcloud_host.yml, host_core/lib/host_core.ex, host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/wasmcloud/native.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/mix.exs, host_core/native/hostcore_wasmcloud_native/Cargo.lock, host_core/native/hostcore_wasmcloud_native/Cargo.toml, host_core/native/hostcore_wasmcloud_native/src/inv.rs, host_core/native/hostcore_wasmcloud_native/src/lib.rs, host_core/native/hostcore_wasmcloud_native/src/objstore.rs, host_core/test/host_core/actors_test.exs
=> Initial commit of invocation chunking support

host_core/lib/host_core/web_assembly/imports.ex
=> Clarified rpc failure due to timeout

host_core/lib/host_core.ex, host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/actors/actor_supervisor.ex, host_core/lib/host_core/config_plan.ex, host_core/lib/host_core/control_interface/server.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/jetstream/client.ex, host_core/lib/host_core/linkdefs/manager.ex, host_core/lib/host_core/nats.ex, host_core/lib/host_core/providers/builtin/logging.ex, host_core/lib/host_core/providers/provider_module.ex, host_core/lib/host_core/providers/provider_supervisor.ex, host_core/lib/host_core/structured_logger.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/test/support/event_watcher.exs
Adds new environment variables to toggle structured logging (default is off because unstructured is easier for humans to read) and at what level. In other words, if you're using structured logging you can override the log level with an environment variable.
=> Support for structured (JSON) logging

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
Bump for `0.54.0` which supports structured logging
=> bump versions for 0.54.0

host_core/mix.exs, host_core/native/hostcore_wasmcloud_native/src/inv.rs, host_core/native/hostcore_wasmcloud_native/src/lib.rs, host_core/native/hostcore_wasmcloud_native/src/oci.rs, wasmcloud_host/mix.exs
I also fixed some clippy lints that had popped up in the NIF
=> chore(*): Bumps app version in preparation for patch release

host_core/lib/host_core/host.ex, host_core/mix.exs, wasmcloud_host/mix.exs
=> Terminate gracefully during SIGTERM

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/native/hostcore_wasmcloud_native/Cargo.toml, host_core/native/hostcore_wasmcloud_native/src/lib.rs, host_core/test/host_core/actors_test.exs
This now makes it so that actor to actor call chunking works as well
as provider to actor call chunking.
Note: I will come back and add a test for actor to actor chunking once
I merge in the new changes to the petclinic
=> fix(host_core): Makes chunking work in all places

host_core/mix.exs, wasmcloud_host/Dockerfile, wasmcloud_host/mix.exs
=> allow host container to gracefully shut down in response to SIGTERM

host_core/lib/host_core/control_interface/server.ex, host_core/lib/host_core/providers/provider_supervisor.ex, host_core/lib/host_core/web_assembly/imports.ex
=> Gracefully handle and prevent launching the same provider twice

wasmcloud_host/rel/config.exs
Signed-off-by: Jordan Rash <15827604+jordan-rash@users.noreply.github.com>
=> Fix for #388

host_core/lib/host_core/host.ex, host_core/lib/host_core/structured_logger.ex
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
=> Formatted files on windows

host_core/native/hostcore_wasmcloud_native/Cargo.lock, host_core/native/hostcore_wasmcloud_native/Cargo.toml
=> bump nats version to fix jetstream kv topic prefix

host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/wasmcloud/native.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/native/hostcore_wasmcloud_native/src/inv.rs, host_core/native/hostcore_wasmcloud_native/src/lib.rs, host_core/test/host_core/actors_test.exs, host_core/test/host_core/wasmcloud/native_test.exs
=> Move trace context from invocation structure to nats headers

host_core/lib/host_core.ex, host_core/lib/host_core/actors/actor_rpc_server.ex, host_core/lib/host_core/actors/call_counter.ex
=> Use round robin to dispatch RPC to actor instances

host_core/config/config.exs, host_core/config/test.exs, host_core/lib/host_core/actors/actor_rpc_supervisor.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/providers/provider_supervisor.ex, host_core/mix.exs, host_core/test/e2e/kvcounter_test.exs, host_core/test/host_core/actors_test.exs, host_core/test/support/event_watcher.exs, wasmcloud_host/config/config.exs, wasmcloud_host/config/test.exs, wasmcloud_host/mix.exs
Fix for https://github.com/wasmCloud/wasmcloud-otp/issues/430
=> gracefully restart an actor's RPC supervisor

wasmcloud_host/lib/wasmcloud_host/actor_watcher.ex, wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
Fixes #421 
I also fixed a warning for hotwatching with terminate_actor
=> Remove "Status" field from Actor panel

host_core/lib/host_core/actors/actor_rpc_server.ex, host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
This release brings in a bug fix for the washboard and performance improvements at a higher parallelism (see #440) 
I added a bit more safety around our RPC call that I meant to fit in the last PR
=> Release 0.55.2

wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
=> fix(web): fix dropdown duplicated ids

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
=> bump host version to v0.56.0

host_core/lib/host_core/control_interface/server.ex
=> account for missing/nil values in control interface commands

host_core/lib/host_core/control_interface/acl.ex
With two actors:
Before:
```
[
{
"id": "MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5",
"image_ref": "wasmcloud.azurecr.io/echo:0.3.5",
"instances": [
{
"annotations": {},
"instance_id": "44f5b008-4390-4718-ae58-c5e059b109ab",
"revision": 4
},
{
"annotations": {},
"instance_id": "abf96602-bbd8-4b5f-ab98-fd0175fc543f",
"revision": 4
}
],
"name": "Echo"
},
{
"id": "MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5",
"image_ref": "wasmcloud.azurecr.io/echo:0.3.5",
"instances": [
{
"annotations": {},
"instance_id": "44f5b008-4390-4718-ae58-c5e059b109ab",
"revision": 4
},
{
"annotations": {},
"instance_id": "abf96602-bbd8-4b5f-ab98-fd0175fc543f",
"revision": 4
}
],
"name": "Echo"
}
]
```
After:
```
[
{
"id": "MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5", …
```
=> remove duplicate actor instances from host inventory

host_core/lib/host_core.ex, host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/actors/actor_rpc_server.ex, host_core/lib/host_core/actors/actor_rpc_supervisor.ex, host_core/lib/host_core/actors/actor_supervisor.ex, host_core/lib/host_core/control_interface/server.ex, host_core/lib/host_core/host.ex, host_core/lib/host_core/jetstream/cache_loader.ex, host_core/lib/host_core/jetstream/client.ex, host_core/lib/host_core/nats.ex, host_core/lib/host_core/providers/provider_module.ex, host_core/lib/host_core/providers/provider_supervisor.ex, host_core/lib/host_core/refmaps/manager.ex, host_core/lib/host_core/web_assembly/imports.ex, host_core/native/hostcore_wasmcloud_native/src/oci.rs
This PR is a quick pass through each `Logger.<level>` call made across the `host_core` module, I attempted to tune up the language and ensure proper context is included for critical areas. While I was at it I fixed a few warnings that consistently popped up.
This PR certainly isn't meant to say all of our logs are now beautiful, complete, and perfect (you can say that if you want 😊) but this is a good step towards revamping some of the logs that weren't clear enough to point to a solution or the offending cause.
=> Audited logs for usefulness and clarity

host_core/lib/host_core/control_interface/server.ex
=> add more validation to control interface server

wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
Bumping to release a few bug fixes and new additions
=> Bumped wasmcloud_host version to 0.57.2

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
=> bump host version to 0.58.0

.github/workflows/release.yml
An unfortunate miss from #490 that made it so the action immediately failed
=> removed hostcore from github release dep

host_core/native/hostcore_wasmcloud_native/src/oci.rs, host_core/test/host_core/wasmcloud/native_test.exs
=> convert OCI refs to lowercase

host_core/lib/host_core/control_interface/acl.ex
=> add contract ID to provider descriptions in inventory

host_core/.credo.exs, host_core/lib/application.ex, host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/claims/manager.ex, host_core/lib/host_core/cloud_event.ex, host_core/lib/host_core/config_service_client.ex, host_core/lib/host_core/control_interface/lattice_server.ex, host_core/lib/host_core/jetstream/client.ex, host_core/lib/host_core/jetstream/legacy_cache_loader.ex, host_core/lib/host_core/jetstream/metadata_cache_loader.ex, host_core/lib/host_core/lattice/lattice_supervisor.ex, host_core/lib/host_core/linkdefs/manager.ex, host_core/lib/host_core/namegen.ex, host_core/lib/host_core/refmaps/manager.ex, host_core/lib/host_core/structured_logger.ex, host_core/test/host_core/policy_test.exs, host_core/test/support/common.exs
This PR addresses the left readability warnings in host_core and the last software design warnings that are not todos. 
Besides the todo warnings, I left out the "refactoring opportunities".
=> Last readability warnings in host_core

host_core/lib/application.ex, host_core/lib/host_core/actors/actor_module.ex, host_core/lib/host_core/actors/actor_supervisor.ex, host_core/lib/host_core/cloud_event.ex, host_core/lib/host_core/control_interface/acl.ex, host_core/lib/host_core/control_interface/host_server.ex, host_core/lib/host_core/control_interface/lattice_server.ex, host_core/lib/host_core/providers/provider_module.ex, host_core/lib/host_core/providers/provider_supervisor.ex, host_core/lib/host_core/vhost/heartbeats.ex, host_core/lib/host_core/vhost/virtual_host.ex, host_core/native/hostcore_wasmcloud_native/Cargo.lock, wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
There is a very specific edge case where if a heartbeat attempts to generate actor and provider data and either the actor module or the provider module are currently in the middle of processing something that can take a long time, or worse, when a ping is requested it emits an ad hoc heartbeat at or near the time of a regular interval heartbeat .... we can create a situation where calling `:get_instance_id` or `:get_link_name` etc on the OTP process can time out.
We've already indicated that when host contents get extremely large, the "old" format of the heartbeat data expands too much. There was even a `TODO` in the code to change this. By changing it so heartbeats don't actually make a call (which drops a message into an OTP process inbox) to each actor process and each provider process …
=> Avoiding an inbox deadlock on heartbeats

wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
The state_monitor.ex process_event for the first host_heartbeat is updated to include the labels in the data argument, 
so it can skip the inventory request to the source host.
Resolves: #525.
=> Use labels from cloud event in state monitor

wasmcloud_host/Makefile, wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.ex, wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.html.heex
Add an explicit warning when files that are too big are uploaded
`next`
Affects provider upload modal of frontend (`wasmcloud_host`), improving it with an explicit alert when files are too big.
Manually verified:
https://user-images.githubusercontent.com/123968127/221045900-2de9ebcf-d95b-414a-b676-c177fc5050f8.mp4
=> feat: alert on provider upload size limit violations

.github/workflows/release.yml
We're missing some EOFs in the heredocs
N/A
v0.61
N/A
N/A
=> add missing EOFs

.github/workflows/host_core.yml, .github/workflows/release.yml, .github/workflows/wasmcloud_host.yml, host_core/native/hostcore_wasmcloud_native/.cargo/config, host_core/native/hostcore_wasmcloud_native/Cargo.lock, host_core/native/hostcore_wasmcloud_native/Cargo.toml, host_core/native/hostcore_wasmcloud_native/rust-toolchain.toml
- update `wasmcloud` (the TinyGo fix has been merged to `main`)
- remove nightly and unstable features
Both of these were merged:
https://github.com/wasmCloud/wasmCloud/pull/305
https://github.com/wasmCloud/wasmCloud/pull/302
=> build(host_core): update `wasmcloud`

.github/workflows/release.yml
This makes sure Linux artifacts are uploaded to CI for local dev using `mix release` with a `BURRITO_TARGET`
=> ci: upload linux artifacts

host_core/mix.exs, wasmcloud_host/chart/Chart.yaml, wasmcloud_host/mix.exs
This PR bumps to v0.63.1 to release #627
=> Bumped app versions to v0.63.1

flake.nix
Fix a dumb debugging artifact from https://github.com/wasmCloud/wasmcloud-otp/pull/638
=> fix(build): remove debugging artifact
