wasmCloud/wasmcloud-otp

- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
- wasmcloud_host/lib/wasmcloud_host_web/controllers/provider_controller.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.leex
Previously, the information provided to the UI did not include contract_id, this PR adds that information to the providers list. In order to accommodate this, the provider map structure has been changed to a list of what I've been calling "instances", which is the combination of a link_name, contract_id, and the host_Id of the host that the provider is running on.
> Restructured provider information and updated UI

- .github/workflows/elixir.yml
- host_core/test/host_core/providers_test.exs
Currently the build pipeline doesn't successfully cache mix deps and dialyzer plts, which costs us about 8.5 minutes out of the 10 minutes of building and testing. This PR will _hopefully_ get that working.
Dependencies and PLTs will need to be rebuilt anytime we add new dependencies, so the first run afterwards may take the full 10 minutes.
> Refactor and upgrade cache action

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/host.ex
- host_core/test/host_core/actors_test.exs
You can now specify a lattice prefix via `WASMCLOUD_LATTICE_PREFIX`, with the default value being `default`
> Support for lattice prefix environment variable

- host_core/lib/host_core/application.ex
- host_core/lib/host_core/host.ex
Fixes #7 
Something about the code feels like I'm missing a cleaner way to do it (e.g. by filtering the connection options by `!= ""`) but it's not difficult to read and gets the job done.
FWIW I tested with user/pass, token, and anonymous. I did not setup a JWT/nk seed authentication challenge to test against, but that's a problem for tomorrow Brooks
> Support different authentication modes for NATS

- host_core/lib/host_core/host.ex
- host_core/lib/host_core/wasmcloud/native.ex
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/test/host_core_test.exs
This will be used later for scheduling.
When starting iex (or the main application) with an environment variable like `HOST_TEST=23`, then we get the following host labels:
```
HostCore.Host.host_labels
%{
"hostcore.arch" => "x86_64",
"hostcore.os" => "linux",
"hostcore.osfamily" => "unix",
"test" => "21"
}
```
Closes #20
> Adds the  function to the HostCore.Host

- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
This was causing a bug with the claims when starting an actor where we were looking for `public_key` and instead needed to look for the claims field `sub`.
@stevelr This is a small fix but just make sure that it works for your testing 👍🏻
> Renamed public_key field to sub for claims

- host_core/lib/host_core/web_assembly/imports.ex
Every actor call to console_log(msg) resulted in a log message "Log from guest: true", 
It was displaying 'true' instead of the message text because of a minor logic bug.
Also I think Wasmex.Memory.read_string should be used instead of read_binary since the mem pointer is a utf8 string.
For the record, console_log is not the recommended way to log from actors. The recommended way is to use a logging provider, but a logging provider doesn't exist for otp yet, so this is the only way to log from an actor. And now it works!
> fix logic error in console_log so it logs messages

- host_core/lib/host_core/control_interface/acl.ex
- host_core/lib/host_core/control_interface/server.ex
In a previous refactor, `Gnat.pub` calls were converted to implicit replies in the message handers for the control interface. This PR fixes an issue where some handlers would simply return `:ok` instead of appropriately responding to the control interface queries.
> Refactored control interface calls to respond appropriately

- host_core/lib/host_core/control_interface/server.ex
Signed-off-by: steve <dev@somecool.net>
as discussed over slack
> change 'uptime' to 'uptime_seconds' in get hosts response

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/control_interface/server.ex
- wasmcloud_host/assets/vendor/wasmcloud/js/tooltips.js
- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/link_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/provider_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/scale_actor_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_actor_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.leex
- wasmcloud_host/lib/wasmcloud_host_web/templates/layout/live.html.leex
Fixes #132, fixes #85 
This PR allows deleting providers from the UI, and scaling actors up and down from the UI. The UI will now handle actor/provider stopped events appropriately, so it will update even if the stop command doesn't originate from the dashboard.
I've also implemented the control interface handler for scale actor, which is an addition but doesn't break anything about the current control interface. Its topic is `wasmbus.ctl.#{lattice_prefix}.cmd.#{host_id}.scale` and expects an actor ID, actor OCI reference, and desired number of replicas. I've designed the scale actor command to work regardless of ocireference for no scaling and scaling down, but in order to scale up an ocireference must be supplied.
If you attempt to scale an actor up that was started from a file in the …
> Allow deleting providers, scaling actors from dashboard

- capability-providers/Makefile
- capability-providers/httpserver/go/main.go
- capability-providers/keyvalue/rust/src/main.rs
As @stevelr mentioned the Rust provider automatically responds to health checks with the new smithy trait, but just for testing and to satisfy the health check I added simple responders in our providers for now.
Fixes #145
> Implemented health check for providers

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/application.ex
- host_core/lib/host_core/oci.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/test/e2e/echo_test.exs
- host_core/test/e2e/kvcounter_test.exs
- host_core/test/host_core/actors_test.exs
- host_core/test/host_core/providers_test.exs
- host_core/test/host_core/wasmcloud/native_test.exs
- host_core/test/host_core_test.exs
This PR introduces the `WASMCLOUD_OCI_ALLOW_LATEST` and `WASMCLOUD_OCI_ALLOWED_INSECURE` environment variables. allow_latest is a boolean to allow the `:latest` tag, and allowed_insecure is a comma-separated list of registries that should be accessed over HTTP rather than HTTPS. 
I also changed the `par_from_bytes` function to return `{:ok, par}` rather than just `par` so we can actually match against the `ok` condition.
> Support OCI environment variables

- capability-providers/httpserver/go/main.go
- capability-providers/keyvalue/rust/Cross.toml
- capability-providers/keyvalue/rust/src/main.rs
- host_core/lib/host_core/host.ex
@brooksmtownsend I couldn't get the cross builds to work, any chance you could regenerate the PARjeezies in this branch? (I also lack the private keys to produce the "right" ones).
@stevelr see the definition for the `LinkDefinition` structs in the Rust and Go example providers for the details you might need to support the changes to the host data struct in any generated code.
> Adding link definitions to HOST_DATA

- host_core/lib/host_core/application.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/lib/host_core/web_assembly/imports.ex
Worth noting that we have not added a timeout to the `linkdefs.put` and `linkdefs.del` RPC calls because those are publishes, not requests, and that's because it's entirely possible (and likely) that capability providers may not actually be up and running at the time the definition is removed or created.
host call RPC timeouts, however, are applicable.
> Adding configurable RPC timeouts

- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/define_link_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/provider_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.leex
- wasmcloud_host/lib/wasmcloud_host_web/templates/layout/live.html.leex
Fixes #166 
This PR took a good bit of refactoring to take on a new structure for the StateMonitor, but overall enables much easier resolutions for #171's sub-issues.
Notable changes:
- In the StateMonitor, we no longer track actors and providers that have host IDs associated with them, rather it's a `hosts` map that is keyed by the host's public key, and contains maps that mimic an inventory for `actors`, `providers`, and `labels`. This will enable a filtering mode to only show resources on a specific host
- The dashboard will query claims and link definitions upon startup (thanks to Jetstream). Established link definitions are immediately shown on the dashboard, and claims are used for further context in the UI. Link definitions, and claims are listened for using the cache loader #169
> Dashboard query resources on startup

- .github/workflows/build_tarballs_manual.yml
- .github/workflows/wasmcloud_host.yml
- wasmcloud_host/Makefile
This PR introduces the `build_tarballs_manual` action, which is essentially a copy of the release section of the `wasmcloud_host` action that can be invoked manually from the Actions tab in Github. This will be useful to produce the tarball artifacts that we plan to use for distribution before we tag an official release in github.
The release image is also built, however it is not pushed to docker.io or azurecr.io. This can be easily changed but I figured we can keep our registry from having pre-release images by just not pushing for the time being.
I've also updated the wasmcloud_host action to reflect the fixes that I discovered, like that docker buildx needs to use the `docker` driver and not the default (`docker-container`, I know, confusing) in order to use the intermediate image …
> Fix manual release action

- wasmcloud_host/assets/css/app.scss
- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/metrics_live.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.leex
- wasmcloud_host/lib/wasmcloud_host_web/router.ex
- wasmcloud_host/lib/wasmcloud_host_web/templates/layout/root.html.leex
Fixes #68 
Most of the changes in this PR revolve around moving the metrics into a separate tab and adding logic to select a host from the list of discovered hosts in the UI. When you select a host, the `Host Info` card will appear with that hosts' labels, lattice prefix, a boolean denoting if it's the "local" host (e.g. the host launched with the dashboard) and a total count of actors and providers running on that host.
Looking for feedback on the code as well as how the UI looks. Does the host selector warrant a different color for the "local" host? Is the UI getting too crowded? Etc.
> Lattice dashboard view

- host_core/lib/host_core/providers/provider_module.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/lib/host_core/wasmcloud/native.ex
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/par.rs
See the linked issue for discussion around why I ended up going with the contract Id and link name for the filename instead of instance IDs.
> Using contract ID and link name for provider executable path

- host_core/lib/host_core/providers/builtin/logging.ex
- host_core/lib/host_core/providers/builtin/numbergen.ex
accept both "Service.Method" and "Method" for invoking methods, e.g., "NumberGen.Random32" and "Random32"
This change allows the host to support new code and is backwards-compatible with old (yesterday's) actors. Once all the interfaces have been regenerated and all the examples updated, we can remove the support for non-prefixed method names.
Signed-off-by: stevelr <steve@cosmonic.com>
> accept new-style method prefixes and old-style method-only names.

- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_actor_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.ex
The 0.12.1 provider is an old-style shared library capability provider rather than a stand-alone executable.
This flummoxed me for a bit, until I found 0.13.1 in https://deploy-preview-51--epic-wiles-f93118.netlify.app/app-dev/create-actor/run/ (I couldn't find any way to list actor versions, other than spamming `docker pull` with random version numbers).
Hopefully this saves the next person some time.
> bump version of placeholder actor + provider

- .github/workflows/build_tarballs_manual.yml
- .github/workflows/host_core.yml
- .github/workflows/wasmcloud_host.yml
This PR is going to run and create a Release that should include the macos and linux tarballs. Once that's verified as working well I'll delete that, revert the manual build to a workflow trigger, and prepare the other 2 actions for our actual release.
EDIT: I've gone through some iteration with this action and verified that now, when we create and push a tag, we will create a release with the name of the tag and the `x86_64-linux-gnu.tar.gz` and `x86_64-macos.tar.gz` artifacts will be attached to that release 🎉 . We can always do the same thing with the manual build action as well, but I've removed the ability to create a release from the manual build action as I don't want test artifacts mucking up the releases page. The artifacts can be found on the `build_tarball_action` page still.
> Update actions, manual test

- host_core/test/host_core/providers_test.exs
- host_core/test/host_core/wasmcloud/native_test.exs
I was cleaning out some old azurecr references including the `httpserver-test` asset which I thought we weren't using anymore, turns out we were still using it for tests.
I think in the future it's not necessary to clean out old references and we should keep it read-only, that was my mistake. I think we should be testing against our actual providers regardless.
> Correct test OCI references

- host_core/lib/host_core/providers/builtin/logging.ex
- host_core/lib/host_core/providers/builtin/numbergen.ex
The acceptance of both format method names was intended to be temporary. All the actors have been updated to use the prefix. Tested with builtins test actor.
Signed-off-by: stevelr <steve@cosmonic.com>
> remove code to allow method names without prefix in builtin providers

- host_core/native/hostcore_wasmcloud_native/src/inv.rs
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/oci.rs
- host_core/native/hostcore_wasmcloud_native/src/par.rs
- host_core/test/host_core/wasmcloud/native_test.exs
- host_core/test/support/constants.exs
Fixes #208 
This PR implements replacing zero or None revision values with the `iat` field on the jwt.
Just a note, the `iat` is implemented as a `u64` integer, while the revision is currently an `i32`. This will cause all wasmCloud actors and providers with a `0` or `None` revision to be unable to load at exactly GMT: Tuesday, January 19, 2038 3:14:07 AM. This is not _that_ far into the future, and we should consider switching revision at least to an `i64`, though I wanted to get thoughts on this before making that change.
I also added some clippy things to reduce the warning output when we compile.
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
> Replace zero revision with iat value

- .github/workflows/build_tarballs_manual.yml
This is only a partial fix because I don't know enough about the Bocker build process yet
to untangle things properly. It is likely we'll need a new image that has rust
and elixir for building purposes, or even better, just build it on the runner
and then `ADD` the file to the elixir docker base image. However, this should
unlock having linux tarballs again
> fix(ci): Fixes linux tarball

- .github/workflows/build_tarballs_manual.yml
The assets were not being compiled into the final tarball
because we weren't webpacking them
> fix(ci): Makes sure webpack actually runs

- .github/workflows/host_core.yml
- host_core/Makefile
- host_core/test/docker-compose.yml
Before this change, we were setting up a redis server only as part of the pipeline
while simultaneously using a docker compose file to get NATS. It is much
easier if the developer and the pipeline use the same targets. So this moves
redis to the docker compose file used for the test and removes it from the pipeline
> feat(tests): Use the same testing in the pipeline and makefile

- host_core/lib/host_core/control_interface/server.ex
Looking up with the atom was giving a `KeyError`. This changes things to
use a string map key
> fix(host_core): Fixes key lookup

- host_core/lib/host_core.ex
My reasoning for this is two-pronged:
1. If you are setting multiple environment variables to configure a host, it's likely that you'll want to persist those for the next time that you close your shell and start up another host. In the case that this is a production machine, and you want to avoid storing sensitive information in a file on disk, you'd have to ensure this file has been created _first_ and then set those variables according to the current logic.
2. With the presence of `host_config.json` and `~/.wash/host_config.json`, those two files should be identical to avoid confusion. If these files are only written when they don't exist, changes in the `host_config.json` relative to the host will not be reflected in `~/.wash/host_config.json` unless it's manually removed.
I sought out …
> Write configuration file regardless if it exists

- wasmcloud_host/lib/wasmcloud_host/lattice/control_interface.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/define_link_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/link_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
Partially addresses #195 
This allows the user to delete a link definition using the washboard, with a nice handy trashcan button.
> [feat] Delete link definitions in Washboard UI

- host_core/lib/host_core.ex
- host_core/lib/host_core/config_plan.ex
- host_core/lib/host_core/jetstream/client.ex
This closes #273. This PR includes the following:
* Re-enable the ability for a host's identity to be supplied via environment variable (`WASMCLOUD_HOST_SEED`)
* Add a new configuration value `js_domain` in the JSON config and `WASMCLOUD_JS_DOMAIN` env var
* No longer writes host configuration to `~/.wash/host_config.json` per discussions
* We now display the current consumer count on the JS stream the host is using. This can be super helpful in troubleshooting domain/leaf node issues (each active wasmCloud host represents an active ephemeral consumer)
> Adds a JetStream domain configuration parameter.

- .github/workflows/wasmcloud_host.yml
- wasmcloud_host/Dockerfile
This PR fixes the release action issue where the Docker image would fail to build for 2 reasons:
1. The docker config location was overwritten by the `docker login` step which was not properly tested when I used my fork (since I disabled the login steps)
2. `git` and `ca-certificates` were not available in the deps-builder image, which failed since we use a git dependency for `vapor`
> [fix] Docker release use buildx

- host_core/lib/host_core/host.ex
This PR publishes the `host_started` event after initialization of the host. It does not yet handle the `host_started` or `host_stopped` events in the dashboard, however, that process incurs some additional complexity with the relationship between those events and heartbeats. Keeping it simple to get the issue done.
Fixes #262
> Published host started command after initialization

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/providers/provider_module.ex
This will allow the lattice observer to store and retrieve the additional metadata about providers and actors.
> Emits claims for provider and actor start events

- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
`debug` is the lowest level log that the `Logger` module supports
> Changed error message for unhandled event

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/par.rs
Adds the human-friendly (e.g. the phrases used by wash during claims `inspect`) time-relative phrases for when claims expire and when they become valid. The events affected are actor_started and provider_started.
> Emits human-friendly relative times for claims expiration and not-before dates

- wasmcloud_host/Makefile
This is a small fix for the Makefile, but when users currently do `make build-image` to build a docker image it will autofill with an empty `SECRET_KEY_BASE`, which unfortunately will cause failures in the web dashboard all the way at runtime. This will use `mix` to generate a secret if it's not supplied.
I also considered just running `mix phx.gen.secret` and committing the dummy value on my own, though it felt a little wrong. Happy to do this if we are OK with committing a dummy secret in exchange for not requiring an elixir toolchain to build an image.
> Generate secret key base for user when building docker image

- .github/workflows/release.yml
- host_core/lib/host_core/control_interface/acl.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
This PR introduces a few fixes:
1. Modified the shape of the actor list in the `host inventory` query to match the control interface structure [here](https://docs.rs/wasmcloud-interface-lattice-control/0.2.2/wasmcloud_interface_lattice_control/struct.ActorInstance.html)
2. removed the unused `${{ env.working-directory }}` from the release action that was causing the GH release to fail
3. Added the `name` and `revision` information to the Actor and Provider inventory queries
4. Bumped to `0.51.1` as this PR fixes a bug, no breaking change
> Fix control interface inventory

- host_core/lib/host_core/jetstream/client.ex
While setting up a more production ready nats cluster with a replicated
lattice cache stream, I noticed that an error was occurring when it tried
to create the stream. For some reason (that I haven't figured out), the
error code returned from NATS if the stream already existed was `400`
instead of `500` when the stream was replicated across multiple nodes.
Because of this error, the lattice cache consumer was never created, leading
to each individual host maintaining its own in memory cache of the claims.
This PR introduces an additional function for checking the streaming
response that takes into account this error code difference. I tested
this against a NATS cluster with a replicated lattice stream and all
the claims appear properly
> fix(jetstream): Handle error when using a stream with multiple replicas

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/heartbeat_emitter.ex
This is ultimately required to give the lattice observer the ability to fill in partial data on actors and providers when monitoring heartbeats.
> Adding instance IDs to actor list on heartbeats

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/test/host_core/actors_test.exs
When a command comes in to terminate `0` instances of an actor, we interpret that as a request to terminate all instances. This PR implements that functionality
> Terminate all instances of an actor with a count of zero

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
Previously when starting an actor from the control interface, if the OCI bytes failed to download we would return `{:stop, err}`. This was inconsistent with other failure modes, so I changed that to `{:error, err}`.
Additionally, some failures for starting providers from the control interface would simply return the result of logging the error, which was `:ok`. I added an additional line to properly return `{:error, err}` here.
Also bump to `0.51.4` for these changes.
> Ensured actors and providers accurately return errors

- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
This PR updates the dashboard to use the new heartbeat format introduced in #309. 
This also fixes #304 and will not cause a dashboard crash in the case of missing claims (instead, the actor name will show as `N/A`)
> Updated dashboard heartbeat shape

- host_core/lib/host_core.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/lib/host_core/heartbeat_emitter.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/namegen.ex
This PR adds support for randomly generated friendly host names. These are not guaranteed to be globally unique, but it's a pretty good chance they'll be unique within a lattice (and there are no real consequences if there's a .001% chance duplicate).
Additionally, while I was in here I fixed a bug that came from assuming that the `~/.wash` directory exists prior to host launch.
```
15:24:22.149 [info]  Host NBLVEPX5AF35DKQVC6MBHGWN4WXIVWCAZX6MHOF6T6OAXH4AEWUXZPTL (misty-ocean-3359) started.
```
> Adding support for friendly host names. Fixing bug with writing config file

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/web_assembly/imports.ex
This PR adds support for publishing invocation success and failure events. These events are directional and so preserve the source and destination of the invocation. This will emit events for comms between actors and providers as well as actor<->actor comms.
Sample events:
```
{
"data": {
"bytes": 51,
"dest": {
"contract_id": "wasmcloud:httpserver",
"link_name": "default",
"public_key": "VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M"
},
"operation": "HttpServer.HandleRequest",
"source": {
"contract_id": "",
"link_name": "",
"public_key": "system"
}
},
"datacontenttype": "application/json",
"id": "b2284728-d463-445d-ac7f-70174255b795",
"source": "NDJ3Z7CBLV3UCPCENHQY34LG3XB7J766DBVG6MM6R34SGN2QDYEYN27K",
"specversion": "1.0",
"time": "2021-12-20T20:38:47.755590Z",
"type": …
```
> Emit invocation success and failure events

- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/chart/README.md
- wasmcloud_host/chart/templates/_helpers.tpl
- wasmcloud_host/chart/templates/deployment.yaml
- wasmcloud_host/chart/templates/role-binding.yaml
- wasmcloud_host/chart/templates/role.yaml
- wasmcloud_host/chart/templates/serviceaccount.yaml
- wasmcloud_host/chart/values.yaml
As part of this effort, this also adds support for custom labels so that the
"router hosts" pattern can be used
> feat(chart): Adds Kubernetes applier support

- .gitignore
- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/lib/host_core/wasmcloud/native.ex
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/client.rs
- host_core/native/hostcore_wasmcloud_native/src/inv.rs
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/oci.rs
- host_core/native/hostcore_wasmcloud_native/src/par.rs
This PR adds experimental support for [Bindle](https://github.com/deislabs/bindle)
to wasmCloud. To be very clear: THIS IS EXPERIMENTAL/could change at any time and its
use is not currently recommended in production. You can now pass a bindle ID
prefaced with `bindle://` and the host will attempt to use a bindle server.
If this PR is merged, I will create a follow up PR for the wasmCloud docs with
example invoices and instructions on how to use it
> feat(host_core): Adds experimental support for bindle

- host_core/lib/host_core.ex
- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/heartbeat_emitter.ex
- host_core/lib/host_core/providers/provider_module.ex
This PR performs the first actor and provider health checks immediately, and sends a host heartbeat as soon as it is initialized.
I've refactored the `Process.send_after` "recursive" calls to be `:timer.send_interval` in the `init` function to make it less error-prone.
> Perform first health checks/heartbeat immediately

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/lib/host_core/heartbeat_emitter.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/lib/host_core/web_assembly/imports.ex
This PR accomplishes the following:
* Host pings now function like proper radar and will emit a heartbeat as soon as they receive a ping
* Health checks are now only emitted when the state changes, which keeps the event log from being spammed by endless healthy status events when running at large-scale steady state.
> Host pings now trigger heartbeats, health status only emitted when it changes

- .gitignore
- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/mix.exs
- host_core/test/host_core/actors_test.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/lib/wasmcloud_host/actor_watcher.ex
- wasmcloud_host/lib/wasmcloud_host/lattice/control_interface.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/scale_actor_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_actor_component.ex
- wasmcloud_host/mix.exs
fixes #332 
This PR makes the start actor accept a `count` field to start multiple instances, and does so in a way that doesn't involve downloading bytes or copying bytes multiple times. Appropriate changes were made in the dashboard to accommodate these changes.
As all of these changes are internal, this is appropriate as a patch bump. The fact that the host did not use the `count` on the start actor payload was a bug.
> ScaleActor fix, added count to StartActor

- host_core/lib/host_core/providers/provider_module.ex
- host_core/mix.exs
- host_core/test/e2e/controlinterface_test.exs
- host_core/test/e2e/echo_test.exs
- host_core/test/host_core/actors_test.exs
- host_core/test/support/event_watcher.exs
Tests that depend on or establish linkdefs, claims, or OCI references need to purge the stream before they run their test. The event watcher is a means-to-an-end here, e.g. it isn't strictly necessary for these tests but the initialization function is useful. Happy to split this out into another piece of logic if needed.
> Ensured tests purge before running

- wasmcloud_host/Dockerfile
Fix missing shared libraries in the final built container on
linux/aarch64 by installing `libssl-dev`. If images for other
architectures already have it installed then this should be a no-op in
those builds.
Closes #302.
> Install libssl-dev in release container

- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
After #339 merged, wanted to bump patch versions to re-release the aarch64 docker container
> Bumped to 0.52.3 for docker re-release

- host_core/README.md
- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/config_plan.ex
- host_core/lib/host_core/config_service_client.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/lib/host_core/wasmcloud/native.ex
- host_core/native/hostcore_wasmcloud_native/src/client.rs
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/oci.rs
- host_core/test/host_core/wasmcloud/native_test.exs
At startup, if the `WASMCLOUD_CONFIG_SERVICE` environment variable is truthy,  the wasmCloud host will attempt to pull supplemental configuration from `wasmbus.cfg.{latttice}`.
This configuration may contain a list of actors to auto-start, a list of providers to auto-start, and a map of registry credentials to be used for pulling from secure OCI/bindle registries.
Not included in this PR (to be added later): support for receiving _push_ updates from a config service as a notification that registry credentials have changed.
> Initial implementation of support for supplemental config via service

- host_core/lib/host_core.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/lib/host_core/host.ex
Control interface server now supports the broadcast message on `registries.put`.
> Add support for pushed registry credentials on control interface

- wasmcloud_host/Dockerfile
Add procps to the Docker image so that it installs `kill` as a binary
instead of just a shell builtin.
Partial fix for #344.
> Add procps to wasmcloud Docker image

- host_core/native/hostcore_wasmcloud_native/src/lib.rs
`par_from_file` in the Rust NIF returns a generic argument error if it
fails to load. It can fail for a number of reasons, so instead of
returning a generic error, return the error message generated from the
underlying provider library.
> Return an error to the host if it fails to read a par file

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/claims/manager.ex
- host_core/lib/host_core/config_service_client.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/lib/host_core/heartbeat_emitter.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/jetstream/client.ex
- host_core/lib/host_core/linkdefs/manager.ex
- host_core/lib/host_core/nats.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/lib/host_core/refmaps/manager.ex
- host_core/lib/host_core/web_assembly/imports.ex
- host_core/test/e2e/controlinterface_test.exs
- host_core/test/host_core/actors_test.exs
- host_core/test/support/event_watcher.exs
Host no longer crashes during a network partition event that disconnects it from its NATS server. We will now see warnings and errors published to the standard logger and the host will automatically recover when connectivity is restored.
While it's a small change, it should contribute greatly to the resiliency of a host in cloud environments.
> Wrapping all NATS calls in safe bubble-wrap

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/control_interface/server.ex
There exists an edge case that results in a double-publish of actor start failed events (control server message handles a start call that results in a Wasmex start failure). However, this is acceptable considering the cost and impracticality of trying to suppress the double-publish. No known downstream consumers of this event would be negatively impacted by receiving it twice.
> Actor module now safely terminates when Wasmex fails to start

- wasmcloud_host/Dockerfile
This PR adds inotify-tools to the installed packages in the release
image of wasmcloud_host. This is necessary for live reload of actors
to work successfully, particularly when used in the docker-compose file
as a bind mount between a remote host and wasmcloud_host. In this case,
the remote system having inotify is not germane to the 
wasmcloud_host application monitoring it's newly visible and watched
files in it's own os environment and package set, which needs inotify for
functioning live-reload.
> [fix] add inotify-tools to wasmcloud_host image

- host_core/lib/host_core.ex
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
The new chunk config was unintentionally adding a value to the original `config`
object rather than adding to the chunk config
> fix(host_core): Avoids crashing when passing a JS domain

- wasmcloud_host/lib/wasmcloud_host_web/live/components/define_link_component.ex
Addresses #369
Utilize the parts option to only split once to ensure correct key=value decoding behavior.
See [Hex docs](https://hexdocs.pm/elixir/String.html#split/3-options)
Matches what wash does. [See wash](https://github.com/wasmCloud/wash/blob/4e9ccc406b7ca996fb1e6153aa93732d62047186/src/util.rs#L133)
> [BUG] Dashboard values cannot handle base64 '=' padding characters

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/web_assembly/imports.ex
* invokes the `_start` function, which is exported by TinyGo's `main()` function
* exposes a fake WASI `fd_write` function because tinygo modules require this even if no code in the module utilizes it.
> Updates the host to support actors written in TinyGo

- host_core/lib/host_core/web_assembly/imports.ex
- host_core/mix.exs
- host_core/test/e2e/kvcounter_test.exs
- wasmcloud_host/mix.exs
Fixes #364 
This PR disambiguates a previous confusing error message for a denied invocation into 2 parts
1. A missing link definition for a contract ID / link name pair (link not configured)
2. A missing capability claim (Actor not allowed to invoke that capability)
Using the kvcounter example, here's what the response error messages look like now. For a successful invocation:
```
> curl localhost:8080/sup
{"counter":1}%  
```
For a kvcounter actor that is missing the `wasmcloud:keyvalue` claim:
```
> curl localhost:8080/sup
{"error":"Host send error Invocation not authorized: missing capability claim for wasmcloud:keyvalue"}%
```
For a kvcounter actor that is either missing a link definition for the `wasmcloud:keyvalue` contract, or does not have a configured link definition for the …
> Disambiguate error message for denied invocation

- .github/workflows/host_core.yml
- .github/workflows/release.yml
- .github/workflows/wasmcloud_host.yml
Updated the host_core and wasmcloud_host actions to build on windows and mac to ensure we don't introduce OS specific issues with updates.
Currently not running tests on those OS'es due to platform-specific dependencies that are not present on mac/windows github-hosted runners
> Changed workflow to run builds on our supported os'es

- .github/workflows/release.yml
- wasmcloud_host/Makefile
The previously released `0.54.5` or `latest` version of the wasmCloud host docker image fails due to an unusable erlang runtime system. This is due to the wasmCloud binary being built on `bullseye` (newer version of debian) but the release image layer is `buster` (older version)
This fix will be released with #392
> Updated release image to bullseye

- host_core/lib/host_core/providers/provider_module.ex
Rather than add the environment variables to the `env_values` field on the host info struct, I decided to propagate the environment variables as actual env vars. This means that capability providers need to do no work in order to handle the environment variables and there won't be any race conditions where a provider might query an env var before it extracts the host info struct.
Initially this is to enable open telemetry in the capability providers but we can also add select variables to the propagation list later
> Propagating selected env vars to providers

- host_core/lib/host_core/config_plan.ex
- host_core/lib/host_core/nats.ex
Add a new environment variable (`WASMCLOUD_ENABLE_IPV6`) that enables
IPv6 support for establishing NATS connections. Without this value, the
Gnat client cannot connect to IPv6-only endpoints.
In theory we could just always enable it, since the underlying `:inet6`
option is dual-stack, but wasmcloud hosts may end up running on systems
that do not support IPv6.
Signed-off-by: Dan Norris <protochron@users.noreply.github.com>
> Add IPv6 support for NATS connections

- host_core/config/config.exs
- host_core/config/test.exs
- host_core/lib/host_core.ex
- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_rpc_server.ex
- host_core/lib/host_core/actors/actor_rpc_supervisor.ex
- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/mix.exs
- wasmcloud_host/config/config.exs
- wasmcloud_host/config/test.exs
- wasmcloud_host/mix.exs
Included in this PR:
* Refactor of manual RPC subscriptions for actors into consumer supervisors
* Subscriptions are now reused per actor and not per instance 
* Misc error handling and edge case enhancements
* Health checks for actors are no longer performed (corresponding events no longer emitted)
> Refactor to consumer supervisors for RPC subscriptions

- host_core/native/hostcore_wasmcloud_native/README.md
- host_core/native/hostcore_wasmcloud_native/src/oci.rs
This PR adds the `OCI_REGISTRY` environment variable which ensures that a specified set of OCI credentials is only used for that specific registry. Without all of these variables specified, anonymous authentication will be used.
An example configuration would be
`OCI_REGISTRY`: `mycustom.azurecr.io`
`OCI_REGISTRY_USER`: `brooksmtownsend`
`OCI_REGISTRY_PASSWORD`: `sup3rs3cur3!`
The motivation for this is both that some OCI registries will try to authenticate you anyways if you supply creds, even if it's a public registry (looking at you ghcr.io) and that it's a mild security risk to send your OCI creds along with each pull request.
Documentation that goes with this PR: https://github.com/wasmCloud/wasmcloud-dev-site/pull/135
> Added OCI_REGISTRY environment variable and docs

- host_core/lib/host_core/host.ex
This is a change in the interest of backwards compatibility and deserializing the hostdata struct
> Renamed structured logging field

- .github/workflows/release.yml
- otel/README.md
- otel/compose.yaml
This PR:
1. Corrects a boolean in the release CI
2. Changes grafana to run on port 5050 to avoid airplay + docker registry conflicts
> Removed a testing artifact for docker CI

- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/chart/templates/deployment.yaml
- wasmcloud_host/chart/values.yaml
Seeking an opinion from @thomastaylor312, do we want to include some of the things from the otel docker compose with this chart?
If not, this should be good to go once 0.55 is released
> Bumped chart to 0.55

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/test/host_core/actors_test.exs
If an annotation map is supplied to the stop actor control interface function (and thereby the `terminate_actor` function), those annotations will be used to narrow the pool of candidate actors against which the stop operation works.
For context, `wadm` will supply such annotations where one annotation contains the "appspec" label, a key that wadm uses to identify which resources belong to which applications.
> Actor termination candidates now filtered by optional annotations

- host_core/mix.exs
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/client.rs
Fixes https://github.com/wasmCloud/wasmcloud-otp/issues/412
Specifically, this PR makes both `reqwest` and the bindle-depended `reqwest` use `rustls` instead of native TLS
This fixes an issue as well with our Docker releases where the host_core NIF is built in a container with openssl 1.0.0 but runs in a container with openssl 1.1.1 (platform deps argh). The solution here is just to not depend on openssl where possible 😄. We are still depending on `libcrypto` with the erlang `:crypto` module, but since we're sourcing our erlang runtime system from the same base container as our running container this is okay as the versions match. (for our tarballs though, this is an issue we'll need to address to run on systems that are using openssl 3)
This PR also updates bindle functionality in the …
> Removed dependencies on openssl in host_core

- host_core/lib/host_core/control_interface/server.ex
A few spots in the control interface didn't propagate trace context into a spawned child task.
> Propagating trace context into Tasks

- wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/provider_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
Here are two changes:
1. Remove createTooltip for element with id prefix `copy_host_id_ `, because there is no button with `copy_host_id_` id prefix. (By the way, the host id copy button uses `popover`(not `tooltip`) to hint `Copied`, see `wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex#273`)
2.  Add element checks in `createTooltip` function, see file `wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex#4`.  Because element with id prefix `stop_hotwatch_button_`  may not exist, see `wasmcloud_host/lib/wasmcloud_host_web/live/components/actor_row_component.ex#42`
With this PR, the console errors can be fixed.
> fix createTooltip error

- host_core/mix.exs
- wasmcloud_host/Makefile
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/config/dev.exs
- wasmcloud_host/config/prod.exs
- wasmcloud_host/config/prod.secret.exs
- wasmcloud_host/lib/wasmcloud_host_web/endpoint.ex
- wasmcloud_host/mix.exs
Previously the dashboard host could be configured at runtime, but the PORT was only configurable at release time. This led to some confusion, and this PR adds `WASMCLOUD_DASHBOARD_HOST` and `WASMCLOUD_DASHBOARD_PORT` which are read at runtime and used to set the host/port.
By default, the host and port will be localhost & 4000 respectively, and this PR actually fixes #417 (in my testing, not setting the dashboard host will allow connections on localhost and 127.0.0.1)
I also added a `make release` target to easily create the release for wasmcloud_host
> Added configurable host and port to the dashboard

- .github/workflows/release.yml
Got the action correct in #451 , but copied the wrong NIF
> Changed host_core release to copy musl nif

- host_core/native/hostcore_wasmcloud_native/.cargo/config
For the x86 musl nif, I forgot to add in the crt-static flag for Rust. You can see a successful run of this at https://github.com/wasmCloud/wasmcloud-otp/actions/runs/2973824076
> Fixed x86 musl nif build error

- wasmcloud_host/lib/wasmcloud_host_web/endpoint.ex
While parsing the port, if the environment variable isn't specified, it ends up piping a `nil` into `String.to_integer()` which panics on startup 😕
> Corrected nil port parse

- host_core/lib/host_core/web_assembly/imports.ex
Fixes #419.
Short circuits the piping in `host_call` to return a better error message when `identify_target` fails to find a target entirely.
I considered turning the entire pipe into the `with` syntax, but that looked too scary for my first `wasmcloud-otp`/Elixir change 😅. Let me know if there's a better way to do this.
Signed-off-by: Matt Wilkinson <matt@mattwilkinson.dev>
> Return better error message when call alias is not found

- host_core/lib/host_core/control_interface/server.ex
- host_core/mix.exs
This PR adds the emission of the ProviderStartFailed event when an identical provider already exists. Previously we ignored this case but that just resulted in confusing cases where the start seemed to be "lost"
> Emit provider start failed when identical provider exists

- host_core/lib/host_core/actors/actor_module.ex
- host_core/test/host_core/actors_test.exs
- host_core/test/support/constants.exs
This PR adds preliminary WASI support, with the following limitations:
* emissions to stdout and stderr currently go into the void (subsequent work can poll them and forward to logger)
* WASI arguments (e.g. psuedo commandline) are empty
* WASI environment variables are empty
* WASI pre-vetted files and directories are empty
The net result of this PR is that WASI modules won't break when loaded, shouldn't have runtime failures, and can access functionality like the clock and random number generator.
Documentation will be forthcoming that outlines the caveats associated with using WASI-based actors.
> Adding WASI support

- host_core/lib/host_core.ex
- host_core/lib/host_core/control_interface/server.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/policy/manager.ex
1. This adds the `js_domain` field to the host information data payload sent to providers during startup. This is only useful if the provider (or underlying RPC library) needs to access things like jetstream for RPC "chunking", etc.
2. Adds the `issuer` field to the host ping response
3. Adds the `issuer` field to the host inventory response
This shouldn't break the control interface clients written in Rust because serde will ignore the unknown field(s). However, @jordan-rash this might break the corresponding Go client (I'm not sure how its JSON deserialization handles unexpected fields)
> Puts js_domain in host info for providers. Adds cluster key (issuer) to host probes

- wasmcloud_host/chart/templates/deployment.yaml
- wasmcloud_host/chart/values.yaml
Just as the PR name states, this is only for development purposes.
My scenario for insecure registries on helm:
I run a home server with microk8s, on a desktop computer, and an insecure registry there. \
It is then used to push images from my laptop, and pull into the wasmcloud deployment. \
Without these changes I cannot deploy actors/providers in any way other than uploading manually, with a GUI.
> (Helm) Allow insecure registries and latest tag, for local/homeserver development

- wasmcloud_host/lib/wasmcloud_host_web/live/components/link_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.html.heex
Signed-off-by: rovast <rovast@163.com>
Add a value column in the link definition table to check the definition information on the dashboard.
> style(web): add values column in link def table

- host_core/lib/host_core/control_interface/server.ex
- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
In #467 I added the `provider_start_failed` event to this scenario, but really we should return a failed ack in this case.
> Quick fix, return quick ack for provider start fail

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/host.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/test/host_core/private_registry_test.exs
- host_core/test/support/constants.exs
This adds `registryType` as a required field on credential maps, which allowed for significant simplification of how credentials for a private OCI/bindle server are looked up. I also added tests for setting/reading registry credentials
> use registry type to extract server names

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_rpc_server.ex
When wasmbus-rpc attempts to deserialize the MessagePack envelope, nils fail to deserialize to an empty Vec. This was causing a bunch of illegible error messages any time the invocation response didn't include a message
> replace nil with empty binary on 'msg' field of invocation responses

- otel/compose.yaml
- otel/grafana.ini
- otel/tempo.yaml
The new docker-compose example supports search traces. So that we do not need to inspect the otel docker log or wasmhost log to get traceID.
> Update otel docker-compose to support seach traces

- host_core/lib/host_core/jetstream/client.ex
- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
This PR removes the "fail early" aspect of the jetstream client. In testing we've seen a few different error messages come from the NATS stream create message, and because we were short-circuiting if we received an unexpected response (even if it was OK to proceed) we broke some new emerging scenarios with stream creates.
After this PR, even if the stream fails to create we'll attempt to create the consumer anyways. Some valid reasons for this include:
1. Stream already exists with that name
1. We proceed safely and create the ephemeral consumer 
3. Stream already exists with that name with a different configuration
1. We proceed safely and attempt to create the ephemeral consumer (which should not fail, unless there's a max number of consumers)
4. The NATS user is allowed to subscribe to …
> Attempt to create consumer regardless of stream response

- .github/workflows/release.yml
As of the `0.58.0` release, we're seeing the host_core Dockerfile fail to build. This is unfortunate, and with an opaque error message difficult to debug. This PR removes this build from our release pipeline, for now.
This is acceptable only because the host_core docker image and tarball don't provide the wasmCloud experience that we want, at this moment. Capability providers that are destined for this image (a musl libc image) need to be compiled _specifically_ with this in mind which is a lot to ask of both our users and ourselves. Until we can transition to architecture-agnostic capability providers, the complexity of compiling our Wasmex package manually and maintaining a Docker image isn't reasonable for the benefit.
> Removed host_core release from actions

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/mix.exs
This change resolves a subtle memory leak. Every time we create an actor we create two child processes - an agent for state, and a `wasmex` genserver for the webassembly module itself. Apparently when using `:normal` as a termination reason, children created with `start_link` are orphaned rather than terminated. This means that the memory consumed by those orphaned children isn't reclaimed.
This changes the shutdown reason to `:shutdown`, which will explicitly cause the GenServer to terminate children and therefore be able to reclaim the resources used by them.
> Fixing orphan processes during actor shutdown

- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
This code adds the host ID of the host that handled the terminate provider message to the shutdown message sent to the provider. This (in another PR) will allow the provider to decide if it was the true target of the shutdown. If it wasn't the target, it will stay running.
Testing Method:
* Updated the HTTP server interface to use new code
* Updated the HTTP server capability provider to use the new interface
* Updated the wasmCloud OTP host (this PR) to include the target host ID on the shutdown message
* Start 2 http server providers , 1 per host
* Issue a stop command for one host
* Observe 1 provider still running
> Add host ID to provider shutdown message

- host_core/mix.exs
- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
Pr #494 is a breaking change, so this is a bump to 0.59.0 instead of releasing `0.58.3`
> Updated version to 0.59.0 for release

- host_core/native/hostcore_wasmcloud_native/src/client.rs
- host_core/native/hostcore_wasmcloud_native/src/inv.rs
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/objstore.rs
We were trying to validate the creator signature as well by default. To keep it simple and transparent to users for now, I made it so we only validate the host signature. In the future we probably want to support a configurable value for the validation strategy
> fix(bindle): Makes bindle verification a little less strict

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_rpc_server.ex
- host_core/lib/host_core/actors/actor_supervisor.ex
I'm starting to address some of the credo warnings. I focused the changes on the host_core/lib/host_core/actors files, using the command `mix credo --strict "lib/host_core/actors/*.ex"` from the host_core folder. 
I left out 3 warnings: 2 are about the #TODOs found in the code. I'd suggest these could be turned into issues here on github so the comments can be removed, fixing the credo warnings. The last warning is about the complexity of the `scale_actor` function, but I was unsure about changing the code too much.
> Credo warnings for host_core/actors/ files

- host_core/test/e2e/controlinterface_test.exs
- host_core/test/e2e/echo_test.exs
- host_core/test/e2e/kvcounter_test.exs
- host_core/test/host_core/actors_test.exs
- host_core/test/host_core/benchmark_test.exs
- host_core/test/host_core/policy_test.exs
- host_core/test/host_core/private_registry_test.exs
- host_core/test/host_core/providers_test.exs
- host_core/test/host_core/wasmcloud/native_test.exs
- host_core/test/host_core_test.exs
- host_core/test/support/common.exs
- host_core/test/support/event_watcher.exs
Another PR for more credo warnings. I focused the changes on the host_core/test files, using the command mix credo --strict "test/**/*ex" from the host_core folder.
I left out 1 TODO warning to not remove that comment. This PR removes a good chunk of the alias/nested modules readability warnings.
> Credo warnings for host_core/test files 

- host_core/lib/application.ex
- host_core/lib/host_core/vhost/config_plan.ex
Closes #480 
This PR removes the double write_json for the host_config.json file and adds a `HOST_CONFIG` env variable, so that it is possible to customize the configuration file to use. 
It adds `:host_config` bindings in config_plan.ex and a nil check in `post_process_config` in case the var was not given, in which case it defaults to `~/.wash/host_config.json`.
> Host_config.json double write fix and customization

- host_core/lib/host_core/control_interface/acl.ex
- host_core/lib/host_core/control_interface/host_server.ex
- host_core/lib/host_core/control_interface/lattice_server.ex
- host_core/lib/host_core/lattice/lattice_supervisor.ex
- host_core/lib/host_core/policy/manager.ex
- host_core/lib/host_core/providers/builtin/numbergen.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/lib/host_core/vhost/config_plan.ex
- host_core/lib/host_core/vhost/files_config_provider.ex
- host_core/lib/host_core/vhost/heartbeats.ex
- host_core/lib/host_core/vhost/virtual_host.ex
- host_core/lib/host_core/wasmcloud/native.ex
- host_core/lib/host_core/web_assembly/imports.ex
This PR tackles the warnings mainly in the folders `lib/control_interface`, `lib/lattice`, `lib/vhost` and `lib/providers`.
I left out the TODO warnings and some Refactoring warnings about the arity of some functions (over 8 args) to not change too much the code. Now the warnings in host_core are reduced to 13 design suggestions (TODO and aliases), 26 code readability issues  and 5 refactoring opportunities.
> More credo warnings cleaning for host_core

- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/par.rs
This bumps to wascap 0.9.1, which is required to support newer webassembly modules (e.g. tinygo and WASI+) signed with newer wascaps.
I had some generics issues with name overlap that led me to have to copy and paste about 7 lines of code. I'm not too worried about the duplication, just irked by the fact that it was necessary to begin with.
If any of the reviewers can figure out how to get the same `impl From` to work the way it used to, that'd be helpful.
> Bumping wascap version to 0.9.1

- host_core/lib/application.ex
This fixes https://github.com/wasmCloud/wasmcloud-otp/issues/527
Credit to @brooksmtownsend for the idea of just using get + Map.put to override a single key
> override primary logger level when structured_log_level is set

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/providers/provider_module.ex
This is potentially a companion to https://github.com/wasmCloud/wasmcloud-otp/pull/530. Removing calls to get instance IDs might be desired anyway to reduce the size of heartbeat messages (in the case where many thousands of actors are running), but after talking with @brooksmtownsend, this seems to address the underlying issue, i.e. that we currently allow looking up a module from the registry before its `init` function has completed
To test, I ran this simple bash script:
```bash
while true; do
wash ctl start actor ghcr.io/brooksmtownsend/wadice:0.2.0 --count 100 --skip-wait && wash ctl get hosts
done
```
On `main`, a host started via `make run` dies in ~10 seconds. With this change, the host stays up for many minutes (until eventually the host died because it was running so many actors …
> move Registry.register calls to after module initialization

- host_core/lib/host_core/jetstream/client.ex
It appears that the current `subjects` filter on this bucket prevents clients from interacting with it. Interacting with a bucket created by a host on `main`:
```
nats stream info KV_LATTICEDATA_f5581cea-c19f-4380-9657-24456c2a917c  
Information for Stream KV_LATTICEDATA_f5581cea-c19f-4380-9657-24456c2a917c created 2023-01-18 17:30:22
Subjects: foobar.$KV.LATTICEDATA_f5581cea-c19f-4380-9657-24456c2a917c.>
...
nats kv ls --js-domain foobar LATTICEDATA_f5581cea-c19f-4380-9657-24456c2a917c
nats: error: unable to fetch keys in bucket: nats: no stream matches subject
```
This can be manually fixed by editing the underlying stream's subjects:
```
nats stream edit -a KV_LATTICEDATA_f5581cea-c19f-4380-9657-24456c2a917c --subjects '$KV.LATTICEDATA_f5581cea-c19f-4380-9657-24456c2a917c.>' …
```
> remove JS domain from LATTICEDATA stream filter subject

- host_core/lib/application.ex
- host_core/lib/host_core/vhost/virtual_host.ex
Caches virtual host configuration in an ETS table. Previous version made GenServer calls to get this data. Moving this to an ETS cache to further reduce the narrow chance of a re-entrant GenServer call
> Caching vhost config

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/lib/host_core/policy/manager.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
- host_core/lib/host_core/vhost/virtual_host.ex
- host_core/test/host_core/policy_test.exs
This PR fixes a few bugs that would prevent actors/providers from starting/invocations from being processed. I also refactored `start_actor` to have significantly less nesting in an attempt to make it easier to read.
I tested these changes by:
- starting a host
- starting actors on the host (including multiple counts)
- starting providers on the host
- linking actors and providers
- issuing requests that generate both actor -> provider and provider -> actor invocations
Everything seems to be working now
Signed-off-by: Connor Smith <connor.smith.256@gmail.com>
> fix various bugs related to policy checks

- host_core/lib/host_core/control_interface/lattice_server.ex
- host_core/lib/host_core/jetstream/client.ex
- host_core/lib/host_core/jetstream/legacy_cache_loader.ex
- host_core/lib/host_core/jetstream/metadata_cache_loader.ex
- host_core/lib/host_core/linkdefs/manager.ex
This addresses two problems:
1) This will change the ID of legacy linkdefs to the new hash-based ID so they can be properly looked up in the new host
2) This actually deletes linkdefs from the metadata cache via the control interface server
Added a link (these are fake IDs)
```
wash ctl link put --link-name default MC7KRLM6QAMNTJY2S7YEMINQ27CADS2UT27EYT4CBQHLZAMGYBRYAIYD VCOX3XM5ZQTX6W7DETWQM4U7JZ7T7EJPUOHNQQX4F3JPJJWCNB6LTWSY wasmcloud:messaging
```
Made sure it shows up in the cache:
```
nats kv ls LATTICEDATA_default
LINKDEF_13599B7EBAA569030B1B9580585B05B2980682D5717F7C9E1910F27339D47F3D
```
Now delete the link:
```
wash ctl link del MC7KRLM6QAMNTJY2S7YEMINQ27CADS2UT27EYT4CBQHLZAMGYBRYAIYD wasmcloud:messaging
```
And now verify that the link is indeed gone:
```
nats kv ls …
```
> Fixes issues with deleting linkdefs

- host_core/lib/host_core/jetstream/metadata_cache_loader.ex
- host_core/lib/host_core/linkdefs/manager.ex
This PR ensures the host emits at least one `linkdef_deleted` cloud event when a link is deleted from the KV bucket
Signed-off-by: Connor Smith <connor.smith.256@gmail.com>
> publish link deleted events

- wasmcloud_host/lib/wasmcloud_host/actor_watcher.ex
- wasmcloud_host/lib/wasmcloud_host/application.ex
- wasmcloud_host/lib/wasmcloud_host/lattice/state_monitor.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/define_link_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/link_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/provider_row_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/scale_actor_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_actor_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/page_live.ex
This PR fixes the Software Design warnings except the TODOs, the Readability warnings except the module_tag missing (I can't give a proper description of all those modules, sorry) and the Refactoring opportunities. 
All the warnings left between host_core and wasmcloud_host are mainly the leftover TODOs, some Refactoring Opportunities and the module_tag descriptions.
> Wasmcloud_host credo warnings

- host_core/lib/host_core/claims/manager.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
This puts the capability provider's contract ID into the claims cache, which in turn stores it in the kv bucket. Once this data is in the claims cache, we can now query it and put it back on the heartbeat without performing a blocking GenServer call
> Putting contract ID back on heartbeat

- host_core/config/config.exs
- host_core/lib/host_core/console_logger.ex
- wasmcloud_host/config/config.exs
- wasmcloud_host/config/dev.exs
- wasmcloud_host/config/prod.exs
- wasmcloud_host/config/test.exs
This logger functions almost the same as the default logger, but includes custom metadata fields
Here are a couple sample logs that include metadata fields:
```
13:31:37.872 [info] version=0.60.0 Started wasmCloud OTP Host Runtime
```
```
13:32:07.034 [debug] oci_ref=wasmcloud.azurecr.io/echo:0.3.4 span_id=63fc79e32f360f0a trace_id=1806094e433956675e6ee30a79c382a6 Start actor request received for wasmcloud.azurecr.io/echo:0.3.4
```
Resolves https://github.com/wasmCloud/wasmcloud-otp/issues/540
Signed-off-by: Connor Smith <connor.smith.256@gmail.com>
> add custom console logger

- wasmcloud_host/lib/wasmcloud_host_web/live/metrics_live.ex
This PR removes a reference to a function that doesn't exist anymore. On main, trying to load metrics results in an internal server error. This references the replacement function, allowing the page to load again
I'm unfamiliar with the metrics page, so I can't attest this is now showing the correct information, but I can say the page loads now
Signed-off-by: Connor Smith <connor.smith.256@gmail.com>
> reference updated function

- host_core/lib/host_core/claims/manager.ex
- host_core/lib/host_core/jetstream/metadata_cache_loader.ex
This PR ensures that when we receive claims over jetstream we attempt to cache call aliases as well for invocation lookups. The symptom that I ran into was two actors running on two wasmCloud hosts, and one host couldn't find the call alias for the other.
Just as verification, and I know these logs are a handful and a half, I put the petclinic API and httpserver on one host, and the petclinic UI (which is invoked via call alias) on a second host. Works great 👍🏻
> Cache call alias when claims are replicated

- .github/workflows/host_core.yml
- .github/workflows/wasmcloud_host.yml
Run of the host_core CI without caching (8 minutes) https://github.com/wasmCloud/wasmcloud-otp/actions/runs/4118238673
Run of the host_core CI with a restored cache (2.5 minutes) https://github.com/wasmCloud/wasmcloud-otp/actions/runs/4118366776
> Cache rust builds during build CI

- host_core/lib/host_core/vhost/virtual_host.ex
This PR fixes #469 
The virtual_host.ex `handle_cast(:do_stop, _timeout_ms}, state)` function invokes `do_purge` and `publish_host_stopped`, then it returns the tuple `{:stop, :shutdown, state}`  triggering the `terminate\2` function.
In `terminate` those two functions are invoked again resulting in a double `host_stopped` event and a double purging of the processes (visible in the logs).
It should be enough not calling those functions immediately in the handle cast but letting `terminate` handle it.
> fix double host stop event 

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/wasmcloudfeature/devcontainer-feature.json
- .devcontainer/wasmcloudfeature/install.sh
This PR is a simple devcontainer that installs elixir, erlang, Rust, nats-server, and a few VScode extensions. This should serve as a good starting point for people who are used to devcontainers / codespaces to develop in a reproduce-able environment!
Try it for yourself, run `devcontainer open` in the root of the repo. This will take some time to build the first time, but I'd like to see if we can publish that image in GHCR sometime
> Added devcontainer for wasmcloud-otp

- host_core/lib/host_core/vhost/heartbeats.ex
- host_core/lib/host_core/vhost/virtual_host.ex
This PR adds the `uptime_seconds` and `version` fields to the `host_started` event. The purpose of this is so the lattice observer will be able to pick up this information immediately, rather than having to wait for the first heartbeat
Before:
```
{
"data": {
"friendly_name": "bold-wind-2335",
"labels": {
"hostcore.arch": "aarch64",
"hostcore.os": "macos",
"hostcore.osfamily": "unix"
}
},
"datacontenttype": "application/json",
"id": "ecfa5fb7-6291-45aa-8687-dd0c46509e62",
"source": "NA3WSC2YF246TZZ2RMI5SOUUBBOL7FWHBRLZZ2JAQNX5MHHJ5JI7TZG5",
"specversion": "1.0",
"time": "2023-02-10T19:46:39.079821Z",
"type": "com.wasmcloud.lattice.host_started"
}
```
After:
```
{
"data": {
"friendly_name": "weathered-ocean-8637",
"labels": {
"hostcore.arch": "aarch64",
"hostcore.os": "macos", …
```
> emit uptime_seconds and version when publishing a host_started event

- host_core/lib/host_core/providers/provider_supervisor.ex
- wasmcloud_host/lib/wasmcloud_host/lattice/control_interface.ex
- wasmcloud_host/lib/wasmcloud_host_web/live/components/start_provider_component.ex
Some providers may need configuration to start, so we can input the configuration in UI, and pass the configuration to host_core.
> Add start provider configuration

- .github/workflows/host_core.yml
- .github/workflows/wasmcloud_host.yml
We're seeing build failures when running dialyzer with cache hits. We suspect it's because the PLTs need to be created
Example failure: https://github.com/wasmCloud/wasmcloud-otp/actions/runs/4356483679/jobs/7614915759
N/A
Next
N/A
Waiting to see if builds pass on this PR
> get & compile deps on cache hits

- host_core/lib/host_core/actors/actor_module.ex
Fixes a regression from #503 that was originally fixed in #496 
N/A
next
This will prevent infinite loops with actors that consume the `wasmbus.evt` topic
See below
I `curl`ed an actor and this is what I got over subscribing on `wasmbus.>`
```
[#2] Received on "wasmbus.rpcevt.default"
traceparent: 00-fa6346c36bd4344aca9baf8457ac95df-4076fe85e61f0dec-01
{"data":{"bytes":107,"dest":{"contract_id":"","link_name":"","public_key":"MCUXITMGLSPAFIMNHQVCC6DLXS6CHJN3NTER2NPP3F6QLR4QHR2SSPCW"},"operation":"HttpServer.HandleRequest","source":{"contract_id":"wasmcloud:httpserver","link_name":"default","public_key":"VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M"}},"datacontenttype":"application/json","id":"61ab0ab7-e4cb-4852-a144-c9823ed94853","sour …
```
> Publish actor invocations on rpcevt

- .github/workflows/host_core.yml
- .github/workflows/release.yml
- .github/workflows/wasmcloud_host.yml
- host_core/Makefile
- wasmcloud_host/Makefile
hexpm, the official erlang/elixir package org, has working base images so using them seems like a good workaround/change
fix local builds/releases under qemu
tbd
0.61.0
this should fix the release issues we were seeing
built locally with the Makefiles
n/a
n/a
builds failed before and don't now
> dockerhub official elixir images are broken under qemu for 1.14.{2,3}

- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
We've been pinned to a specific SHA of bindle because at the time v0.9 hadn't been released. It has now
N/A
Next
N/A
I'll be honest, I didn't test this. Besides compiling, what should be done?
> unpin from specific SHA of bindle

- .github/workflows/release.yml
- host_core/Makefile
- wasmcloud_host/Makefile
natively built images can stay on otp 25
release builds still broken for cross compilation
https://github.com/erlef/docker-elixir/issues/61
0.61.0
n/a (allows release to go forward)
built using linux/amd64 host
n/a
n/a
built on linux/amd64 host with `--platform linux/arm64`
> revert to otp 24 for cross-built images as otp 25 fails under qemu

- host_core/mix.exs
- wasmcloud_host/mix.exs
release broke on windows
n/a
next
n/a
local
n/a
n/a
local
> fix mix.exs assemble steps for windows

- .github/workflows/release.yml
- wasmcloud_host/Makefile
compilation so we will comment them out for now... amd64 is ok
remove static arm64 releases for now since cross-compiling is error prone
#572 and #570 
next
amd64 static releases pass
locally
n/a
n/a
locally built
> changes to get static builds were not quite ready yet for cross

- .github/workflows/release.yml
- host_core/Dockerfile.static
- wasmcloud_host/Dockerfile.static
different node. also might be helpful if we ever need to figure out what was in a static build image base
broken release
#570
#572 
next
n/a
can't test outside GH actions unfortunately
n/a
soon
n/a
> need to push static image build in case build gets scheduled on

- host_core/Dockerfile.static
- wasmcloud_host/Dockerfile.static
Dockerfile.static issues
n/a
next
fix release build
ran `make build-image-static` locally
n/a
n/a
`make build-image-static`
> small mistake in Dockerfile.static FROM definition

- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/oci.rs
When fetching an OCI image, the code checked whether a cache existed and pulled the image if it did not exist.
Now it checks the cache file she with the latest oci image she to verify whether the latest image is cached and pulls if the she digest does not match.
NA
next
Users will have no breaking changes. 
Manual testing was performed using the nif since unit tests are not supported yet. End to end tests can be added as future work.
Manual unit tests were performed. Following is a log showing a sha digest match on 3 cache files resulting in no additional image pulls.
```
..cache file: "/var/folders/k6/7fp1nc5s7w1987jh7vzpnyn40000gn/T/wasmcloud_ocicache/wasmcloud_azurecr_io_echo_0_3_1.bin" 
oci image: Reference { registry: "wasmcloud.azurecr.io", …
```
> Compare OCI sha with disk cache sha before pulling an image

- host_core/lib/host_core/providers/provider_module.ex
- host_core/test/host_core/providers_test.exs
From the discussions of the following issues, providers should emit the health events on the `wasmbus.evt` topic.
Please let me know if I misunderstood what was being asked in those issues or if there is something missing.
- #517 
- #519 
Next
N/A
I've added a test in test/host_core/provider_tests.exs to start a provider from file and wait on the health_check events. It first waits for the health_check_passed event when the provider is started and afterwards waits for the health_check_status event once, which is emitted every 30 seconds.
I've launched nats and subscribed to `wasmbus.evt.*` and to ">". 
I've used `make run` from the dashboard project and from the web page started a provider from file to checkout that the health_status event was …
> Add provider health status event

- host_core/lib/host_core/providers/provider_module.ex
Host heartbeats include the contract ID on providers, but the provider health check events do not. This adds the contract ID to health check events
N/A
Next
Downstream consumers (e.g. wadm, lattice observer) can consume the contract ID on provider health events now
I started a host, started a provider, and waited for health check events:
```
{"data":{"contract_id":"wasmcloud:httpserver","link_name":"default","public_key":"VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M"},"datacontenttype":"application/json","id":"1921d01d-e9d9-4092-bd2e-2a5fafff1a99","source":"NBXBB5KSNH6MPK5ZRNDUDTHBAPKGZTERVSW6UDH4NKOJPNJRXCPVN5KA","specversion":"1.0","time":"2023-03-20T20:45:14.903196Z","type":"com.wasmcloud.lattice.health_check_passed"}
```
``` …
```
> add provider contract ID to health check events

- wasmcloud_host/chart/Chart.yaml
- wasmcloud_host/mix.exs
Simply bumping the release versions for wasmcloud_host to match host_core before cutting the first RC
> Bumped mix.exs in wasmcloud_host and chart

- .github/workflows/release.yml
We currently derive `app-version` from mix.exs. This works for "real" releases, but not for RCs or other test tags. Instead we should derive `app-version` from the tag name. This should be accessible via `GITHUB_REF`, after we trim the leading `/refs/tags/`
(Bash & GHA experts should double-check this syntax. I'm not confident in it)
> derive version from GITHUB_REF rather than mix.exs

- host_core/lib/host_core/vhost/virtual_host.ex
Typo in provider link name key of virtual host auto-starts config introduced [here](https://github.com/wasmCloud/wasmcloud-otp/commit/724605a2e10b619c454800947b7938a3a1a837dc#diff-d4745423f0f8ec260efa51ead41d1be18ecc4edc5b2534072816391a6d7b0780R543):
`linkeName` -> `linkName`
Presumably this would fail to supply the configured link name to the auto-started provider.
Commented on in the original PR [here](https://github.com/wasmCloud/wasmcloud-otp/pull/529#issuecomment-1481987232)
`next`
No changes required from dependents.
Test suite did not exercise the code in question.
Built on platform(s):
Whatever `make test` builds with docker.
Tested on platform(s):
Untested
None
> correct key for provider link name in supp config during vhost autostarts

- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
Version 0.10.0 of wascap doesn't properly validate the hashes of modules signed with wascap versions 0.9.0 through 0.10.0. The 0.10.1 version fixes this
N/A
Next (0.62.0)
Without this, wasmCloud host will reject wasm modules signed by 0.9.0/0.10.0 of wascap, breaking functionality
N/A
Tested this manually with a number of different modules, including old ones and ones signed with 0.9.0
> Bumping the version of wascap to the newest

- .github/workflows/release.yml
- wasmcloud_host/Dockerfile
As of the latest attempted release, something about `cross` trying to use Rust nightly to build our native NIF fails. This PR resolves the issues by moving the NIF builds inside of the Docker image for both aarch64/x86 linux, which arguably keeps this simpler.
Related to #589, this is a temporary workaround to simplify the CI and avoid the failure
#589 is the issue, that this doesn't quite fix but works around
v0.62.0
No change, even if you built the image locally you build inside the docker image so this is just making the process the same everywhere.
I built the image locally!
> Fix native NIF compilation with cross for release

- host_core/lib/host_core/wasmcloud/rpc_invocations.ex
- host_core/lib/host_core/wasmcloud/runtime_server.ex
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/atoms.rs
- host_core/native/hostcore_wasmcloud_native/src/environment.rs
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/wasmruntime.rs
- host_core/test/host_core/actors_test.exs
Version 0.62 does not currently emit any information when actors log using the builtin capability provider. This adds that support back in a way that is compatible with previous hosts.
This supercedes @rvolosatovs 's PR #591 because, in all honesty, I couldn't figure out how to make a PR off of his PR and didn't have rights to force push to his PR
0.62
All deployments of wasmCloud relying on actor log emissions with or without structured host logging.
There is an explicit actor test for performing logging and random number generation to exercise the builtins
` test/host_core/actors_test.exs:639` is the test that exercises builtins (including logging). This test passes and produces the expected output in stdout.
Manually verified this works as …
> Adding support for builtin providers and deferring builtin logging to the OTP host

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/actors/actor_rpc_server.ex
- host_core/lib/host_core/wasmcloud/native.ex
- host_core/lib/host_core/wasmcloud/runtime.ex
- host_core/lib/host_core/wasmcloud/runtime_server.ex
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/inv.rs
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/wasmruntime.rs
Fixes #590 
More information will follow once the wasmcloud/wasmcloud PR merges as implementation may change
This PR uses the updated wasmcloud library (https://github.com/wasmCloud/wasmCloud/pull/298) to propagate the `span_ctx` through the entire invocation chain, ensuring that we are reconnecting traces when actors do a host_call.
#590 
v0.62.0
Traces work as expected
While testing the runtime I was able to verify this connects host calls in tracing
> Fix tracing propagation for host_calls (fixes #590)

- .devcontainer/devcontainer.json
This PR simply fixes a small issue I found when trying out our codespace, little copy/paste fail from the wash codespace.
N/A
N/A
Folks won't have to select the `wash` workspace manually
Made sure it worked in the branch 
> Corrected workspace path

- .github/workflows/release.yml
- host_core/config/release_prod.exs
- wasmcloud_host/config/release_prod.exs
This PR removes [`cross-rs`](https://github.com/cross-rs/cross) for cross-platform builds, falling back to per-platform builds.
This was necessary because the `.dll`s that `cross-rs` was building seemed to not be correct/working on Windows
#566 
https://github.com/wasmCloud/wash/issues/494
`next`
Windows users will be able to use published releases
N/A
N/A
Build was run manually and in CI, then tested on both windows and linux
> fix: remove cross-rs for native builds

- wasmcloud_host/Dockerfile
Fix broken docker build due to missing `rust` toolchain
#566 
`next`
Consumers can use docker builds
N/A
Tested locally via `make build-image`
> fix(ci): docker build

- wasmcloud_host/chart/Chart.yaml
Bumps chart version to `0.6.11` which includes the v0.62.0 release
> Bumped chart version

- .github/workflows/release.yml
@brooksmtownsend noticed we published v0.62.0 of the host with the leading `v` included in the tag name. That goes against the convention we've used elsewhere, so I've removed it
Next
N/A
Tested with bash:
```bash
❯ GITHUB_REF_NAME=v0.62.0
❯ echo ${GITHUB_REF_NAME#v}
0.62.0
❯ echo ${GITHUB_REF_NAME#z}
v0.62.0
```
> strip leading v from tags

- host_core/native/hostcore_wasmcloud_native/src/wasmruntime.rs
When detecting host call errors, the NIF is returning the raw bytes from the error. Now we parse as a string before returning
Fixes https://github.com/wasmCloud/wasmcloud-otp/issues/606
Next
Much more clear error messages on host calls
Tested manually with `make run`:
- started the HTTP server provider
- started the XKCD actor
- linked them
- invoked the XKCD actor, which tries to call the HTTP client provider. This isn't running, so the host generates an error, which is now parsed as a string:
```
{"error":"actor: sending req: Host send error Host call function failed: Invocation not authorized: missing link definition for wasmcloud:httpclient on default"}
```
> parse invocation errors as strings

- host_core/lib/host_core/actors/actor_module.ex
- host_core/lib/host_core/providers/provider_module.ex
This adds `annotations` to the `actor_stopped` and `provider_stopped` events
Resolves https://github.com/wasmCloud/wasmcloud-otp/issues/609
Next
wadm can read annotations off stop events now
Notice both started and stopped events have annotations on them:
```
{"data":{"annotations":{"foo":"bar"},"api_version":"n/a","claims":{"call_alias":null,"caps":["wasmcloud:httpserver"],"expires_human":"never","issuer":"ACOJJN6WUP4ODD75XEBKKTCCUJJCY5ZKQ56XVKYK4BEJWGVAOOQHZMCW","name":"Echo","not_before_human":"immediately","revision":4,"tags":[],"version":"0.3.4"},"image_ref":"wasmcloud.azurecr.io/echo:0.3.4","instance_id":"a7bf8b1a-5162-450d-b28c-90ed5fb7b92b","public_key":"MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5"},"datacontenttype":"application/json","id":"88410ca3-ac67-48c8-9517-b92 …
```
> add annotations to actor_stopped and provider_stopped events

- host_core/lib/host_core/providers/provider_module.ex
Looks like we missed one letter on the Provider stopped event :)
> Annotations typo fix

- host_core/lib/host_core/control_interface/host_server.ex
- host_core/lib/host_core/providers/provider_module.ex
- host_core/lib/host_core/providers/provider_supervisor.ex
Fixes a bug that allows an edge case race condition to start the same provider twice on the host
#625
vNext
Probably only reproducible by humans once in a blue moon, but this fix will make CI testing and `wadm` not be able to break the host this way
Followed reproduction steps before and after and made sure problem goes away
No
N/A
Manually ran shell script to generate two concurrent launch provider requests, each for a different OCI reference (note the identical timestamps down to the millisecond):
```
10:30:55.549 [debug] Received host control interface request on wasmbus.ctl.default.cmd.NDOYD5XD62SLW7DKUZZOVL3NCYUPQBXVUR3O3QL6AABUGJGHPYYM4APD.lp
10:30:55.549 [debug] Received host control interface request on …
```
> Blocks multiple concurrent provider starts of the same public key + link name

- .github/workflows/release.yml
- host_core/Dockerfile
- wasmcloud_host/Dockerfile
Feature or Problem
The current 0.63 builds only have the arm64 architecture available for docker images
Release Information
Next. However, if we can find a way to rebuild the 0.63.1 images using this, that would be nice
Testing
This is being tested with a run of the pipeline before changing back the vars
> fix(ci): Builds docker images for both supported arches

- host_core/lib/host_core/jetstream/metadata_cache_loader.ex
* Adds a few extra bits of very useful information to the debug logs.
* Adds a couple of fallthrough handlers to avoid the function pattern mismatch type of errors
Note that there were reports of the metadata cache loader "stopping". I can't reproduce this and, more importantly, the way Gnat works it traps the call to `request` in an exception handler so the worst case scenario for a Gnat consumer supervisor would be an error log dump. If it stops getting bucket updates, then that may be caused by something else.
Regardless, the changes made here add more useful troubleshooting information and certainly don't make things worse.
> tiny logging improvement

- .github/workflows/release.yml
- flake.lock
- flake.nix
- host_core/lib/remove_nix_store_refs.ex
- host_core/mix.exs
- wasmcloud_host/mix.exs
- fix `nix flake show`
- remove the `secret-key-base` hack, use actual env variables and `--impure`
- remove `/nix/store` references from Elixir releases. This one is a fun one, Elixir is used to build the project and then copies itself to the release - we would not be able to build using "patched" Elixir, since `/bin/sh` etc. does not (and should not) exist in `nix` sandbox during build, therefore we patch these out as part of the `mix` build
Pull an artifact from a CI run as usual and test in a Docker container, e.g. `docker run --rm -it -v$(pwd):$(pwd) -w$(pwd) ubuntu` from a directory containing the binary. Run (let it fail) and inspect `~/.local/share/.burrito/*`. Currently there's just one shebang with `nix` store ref, in cgi handler, but we should not use that anyway
Built on …
> build: remove `nix` store paths from releases 

- flake.nix
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
> build(native): switch to `wasmcloud-otp`

- host_core/lib/host_core/claims/manager.ex
- host_core/native/hostcore_wasmcloud_native/Cargo.lock
- host_core/native/hostcore_wasmcloud_native/Cargo.toml
- host_core/native/hostcore_wasmcloud_native/src/lib.rs
- host_core/native/hostcore_wasmcloud_native/src/par.rs
- wasmcloud_host/package-lock.json
This adds support for the `config_schema` field in capability provider claims. It is supposed by both the internal claims cache and the KV bucket, as well as extraction from the PAR file itself.
Querying claims from the lattice (asking the host):
```
wash ctl get claims -o json
[warn] `wash ctl get claims` has been deprecated in favor of `wash get claims` and will be removed in a future version.
{
"claims": {
"claims": [
{
"call_alias": "",
"caps": "",
"config_schema": "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"description\":\"wasmCloud HTTP Server Provider Link Definition configuration specfiication\",\"properties\":{\"address\":{\"default\":\"127.0.0.1:4000\",\"description\":\"An address and port combination on which to …
```
> Adding host support for json schemas in claims

- host_core/lib/host_core/actors/actor_supervisor.ex
- host_core/mix.exs
- wasmcloud_host/mix.exs
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>
This PR fixes an error log that had the wrong escape character for when an actor was loaded from file.
N/A
0.63.2
I ensured this was the proper escape code using `iex`.
> fix(ctl): fix actor file error log
